---

- name: Configure APT
  template:
    src: '{{ item }}.j2'
    dest: '/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items:
    - 'etc/apt/apt.conf.d/25no-recommends.conf'
    - 'etc/apt/apt.conf.d/70aptitude'

- name: Ensure that APT default configuration is absent
  file:
    path: '{{ item }}'
    state: 'absent'
  when: apt__remove_default_configuration|d()
  with_items:
    - '/etc/apt/apt.conf'

- name: Load default APT mirrors configuration
  include_vars: '{{ item }}'
  with_first_found:
    - 'apt__default_mirrors_{{ apt__default_mirrors_lookup | lower }}.yml'
    - 'apt__default_mirrors.yml'
  when: apt__default_mirrors is undefined

- name: Load default APT sources configuration
  include_vars: '{{ item }}'
  with_first_found:
    - 'apt__default_sources_{{ apt__default_sources_lookup | lower }}.yml'
    - 'apt__default_sources.yml'
  when: apt__default_sources is undefined

- name: Enable delayed APT configuration
  set_fact:
    apt__keys_delayed_enabled: '{{
      (apt__keys_delayed               |d([]) | list) +
      (apt__group_keys_delayed         |d([]) | list) +
      (apt__host_keys_delayed          |d([]) | list) }}'
    apt__repositories_delayed_enabled: '{{
      (apt__repositories_delayed       |d([]) | list) +
      (apt__group_repositories_delayed |d([]) | list) +
      (apt__host_repositories_delayed  |d([]) | list) }}'
    apt__sources_delayed_enabled: '{{
      (apt__sources_delayed            |d([]) | list) +
      (apt__group_sources_delayed      |d([]) | list) +
      (apt__host_sources_delayed       |d([]) | list) }}'
  when: (ansible_local|d() and ansible_local.apt|d())

- name: Combine lists of default and user APT mirrors and sources
  set_fact:
    apt__keys_combined: '{{
      (apt__keys               |d([]) | list) +
      (apt__group_keys         |d([]) | list) +
      (apt__host_keys          |d([]) | list) +
      (apt__keys_delayed_enabled|d([]) | list) }}'
    apt__repositories_combined: '{{
      (apt__repositories       |d([]) | list) +
      (apt__group_repositories |d([]) | list) +
      (apt__host_repositories  |d([]) | list) +
      (apt__repositories_delayed_enabled|d([]) | list) }}'
    apt__mirrors_combined: '{{
      (apt__mirrors            |d([]) | list) +
      (apt__group_mirrors      |d([]) | list) +
      (apt__host_mirrors       |d([]) | list) +
      (apt__default_mirrors    |d([]) | list) }}'
    apt__sources_combined: '{{
      (apt__default_sources    |d([]) | list) +
      (apt__sources            |d([]) | list) +
      (apt__group_sources      |d([]) | list) +
      (apt__host_sources       |d([]) | list) +
      (apt__sources_delayed_enabled|d([]) | list) }}'

- name: Configure custom APT keys
  apt_key:
    data: '{{ item.data   | default(omit) }}'
    file: '{{ item.file   | default(omit) }}'
    id:   '{{ item.id     | default(omit) }}'
    keyring: '{{ item.keyring | default(omit) }}'
    keyserver: '{{ item.keyserver | default(omit) }}'
    state: '{{ item.state | default("present") }}'
    url: '{{ item.url | default(omit) }}'
  with_items: '{{ apt__keys_combined }}'
  when: (item.url is defined or item.data is defined or item.id is defined or item.file is defined and
         (item.state is undefined or item.state is defined))

- name: Configure custom APT repositories
  apt_repository:
    repo: '{{ item.repo }}'
    state: '{{ item.state | default("present") }}'
    update_cache: False
  with_items: '{{ apt__repositories_combined }}'
  when: ((item.repo is defined and item.repo) and
         (item.state is undefined or item.state is defined))

- name: Divert original /etc/apt/sources.list
  command: dpkg-divert --quiet --local --divert /etc/apt/sources.list.dpkg-divert --rename /etc/apt/sources.list
  args:
    creates: '/etc/apt/sources.list.dpkg-divert'
  when: apt__sources_combined

- name: Configure main APT package sources
  template:
    src: 'etc/apt/sources.list.j2'
    dest: '/etc/apt/sources.list'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: apt__register_sources_list
  when: apt__sources_combined

- name: Move sources.list out of the way before reversion
  # only remove sources.list if sources.list.dpkg-divert exists
  command: rm -f /etc/apt/sources.list
  args:
    removes: '/etc/apt/sources.list.dpkg-divert'
  when: not apt__sources_combined

- name: Remove diversion of original /etc/apt/sources.list
  command: dpkg-divert --quiet --local --rename --remove /etc/apt/sources.list
  args:
    removes: '/etc/apt/sources.list.dpkg-divert'
  when: not apt__sources_combined

- name: Update package lists
  apt:
    update_cache: True
    cache_valid_time: '{{ omit if (apt__register_sources_list|changed) else apt__update_cache_early }}'

- name: Install required packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - '{{ apt__base_packages }}'
  tags: [ 'role::apt:install' ]

