---

- name: Configure APT to use a proxy server
  template:
    src: 'etc/apt/apt.conf.d/000apt-cacher-ng-proxy.j2'
    dest: '/etc/apt/apt.conf.d/000apt-cacher-ng-proxy'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: (apt__enabled|d() | bool) and ((apt__proxy_url is defined and apt__proxy_url is string and apt__proxy_url) or apt__proxy_bypass_for_bugs_debian_org or apt__proxy_direct_urls is defined) 

- name: Configure APT to not use a proxy server
  file:
    path: '/etc/apt/apt.conf.d/000apt-cacher-ng-proxy'
    state: 'absent'
  when: (apt__enabled|d() | bool) and not ((apt__proxy_url is defined and apt__proxy_url is string and apt__proxy_url) or apt__proxy_bypass_for_bugs_debian_org or apt__proxy_direct_urls is defined)

- include: apt.yml
  when: (apt__enabled|d() | bool)

- include: update_notifications.yml
  when: (apt__enabled|d() | bool)

- name: Remove old unattended-upgrades configuration
  file:
    path: '/etc/apt/apt.conf.d/{{ item }}'
    state: 'absent'
  with_items:
    - '25auto-upgrades.conf'
    - '55unattended-upgrades.conf'
  when: (apt__enabled|d() | bool)

- name: Make sure that Ansible local facts directory exists
  file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  when: (apt__enabled|d() | bool)

- name: Save APT local facts
  template:
    src: 'etc/ansible/facts.d/apt.fact.j2'
    dest: '/etc/ansible/facts.d/apt.fact'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: (apt__enabled|d() | bool)

